"""add_conversational_quality_fields

Revision ID: 51d0e88085b3
Revises: a1e6f0e6a1eb
Create Date: 2025-11-05 21:02:49.391038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51d0e88085b3'
down_revision: Union[str, Sequence[str], None] = 'a1e6f0e6a1eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('dialogue_techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Successful conversational techniques used'))
    op.drop_index(op.f('cases_embedding_idx'), table_name='cases', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('consultations', sa.Column('conversational_quality', sa.Float(), nullable=True, comment='Quality score for conversational naturalness (0-1)'))
    op.add_column('consultations', sa.Column('dialogue_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Captured dialogue techniques and patterns used'))
    op.drop_index(op.f('fca_knowledge_category_idx'), table_name='fca_knowledge')
    op.drop_index(op.f('fca_knowledge_embedding_idx'), table_name='fca_knowledge', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_fca_knowledge_category'), 'fca_knowledge', ['category'], unique=False)
    op.drop_index(op.f('memories_embedding_idx'), table_name='memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('pension_knowledge_category_idx'), table_name='pension_knowledge')
    op.drop_index(op.f('pension_knowledge_embedding_idx'), table_name='pension_knowledge', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_pension_knowledge_category'), 'pension_knowledge', ['category'], unique=False)
    op.drop_index(op.f('rules_embedding_idx'), table_name='rules', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('rules_embedding_idx'), 'rules', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_pension_knowledge_category'), table_name='pension_knowledge')
    op.create_index(op.f('pension_knowledge_embedding_idx'), 'pension_knowledge', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('pension_knowledge_category_idx'), 'pension_knowledge', ['category'], unique=False)
    op.create_index(op.f('memories_embedding_idx'), 'memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_fca_knowledge_category'), table_name='fca_knowledge')
    op.create_index(op.f('fca_knowledge_embedding_idx'), 'fca_knowledge', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('fca_knowledge_category_idx'), 'fca_knowledge', ['category'], unique=False)
    op.drop_column('consultations', 'dialogue_patterns')
    op.drop_column('consultations', 'conversational_quality')
    op.create_index(op.f('cases_embedding_idx'), 'cases', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('cases', 'dialogue_techniques')
    # ### end Alembic commands ###
