"""Initial migration with pgvector support

Revision ID: a7b3073fdead
Revises: 
Create Date: 2025-11-01 21:55:56.929871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'a7b3073fdead'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('customer_situation', sa.String(), nullable=False),
    sa.Column('guidance_provided', sa.String(), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('conversation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_customer_id'), 'consultations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_consultations_start_time'), 'consultations', ['start_time'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_accessed', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('memory_type', sa.Enum('observation', 'reflection', 'plan', name='memory_type_enum'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('importance >= 0 AND importance <= 1', name='memories_importance_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principle', sa.String(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='rules_confidence_check'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Create vector similarity indexes using HNSW (supports >2000 dimensions)
    op.execute('CREATE INDEX IF NOT EXISTS memories_embedding_idx ON memories USING hnsw (embedding vector_cosine_ops)')
    op.execute('CREATE INDEX IF NOT EXISTS cases_embedding_idx ON cases USING hnsw (embedding vector_cosine_ops)')
    op.execute('CREATE INDEX IF NOT EXISTS rules_embedding_idx ON rules USING hnsw (embedding vector_cosine_ops)')


def downgrade() -> None:
    """Downgrade schema."""
    # Drop vector indexes
    op.execute('DROP INDEX IF EXISTS rules_embedding_idx')
    op.execute('DROP INDEX IF EXISTS cases_embedding_idx')
    op.execute('DROP INDEX IF EXISTS memories_embedding_idx')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    op.drop_table('memories')
    op.drop_index(op.f('ix_consultations_start_time'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_customer_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_table('cases')
    # ### end Alembic commands ###
